#!/usr/bin/env python3
"""Blind-prediction baselines + ROC on the held-out cohort (paper Table 2).

Usage:
  python scripts/blind_baselines.py --manifest artifacts/blind.jsonl

Reads the per-model manifest (certificate_score, val_loss, param_count,
is_generalizer) and reports Precision / Recall / Specificity / Balanced
accuracy / AUROC with Wilson 95% CIs for:
  - the PIV certificate (pre-registered threshold tau=0.8),
  - always-positive,
  - prevalence-matched random,
  - val_loss < median,
  - param_count > median.
Writes tables/blind_baselines.tex and figures/roc_blind.pdf (matplotlib
optional).
"""
import argparse
import json
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import piv  # noqa: E402
from piv.casestudy import CERTIFICATE  # noqa: E402


def metrics(pred, y):
    tp = sum(p and t for p, t in zip(pred, y))
    fp = sum(p and not t for p, t in zip(pred, y))
    fn = sum((not p) and t for p, t in zip(pred, y))
    tn = sum((not p) and (not t) for p, t in zip(pred, y))
    prec = tp / max(tp + fp, 1)
    rec = tp / max(tp + fn, 1)
    spec = tn / max(tn + fp, 1)
    return dict(precision=prec, recall=rec, specificity=spec,
                balanced_acc=(rec + spec) / 2,
                ci_precision=piv.wilson_ci(tp, max(tp + fp, 1)),
                ci_recall=piv.wilson_ci(tp, max(tp + fn, 1)),
                counts=(tp, fp, fn, tn))


def auroc(scores, y):
    pairs = sorted(zip(scores, y))
    pos = sum(y); neg = len(y) - pos
    if pos == 0 or neg == 0:
        return float("nan")
    rank_sum = 0.0
    i = 0
    while i < len(pairs):
        j = i
        while j < len(pairs) and pairs[j][0] == pairs[i][0]:
            j += 1
        avg_rank = (i + j + 1) / 2  # 1-based average rank for ties
        rank_sum += avg_rank * sum(1 for s, t in pairs[i:j] if t)
        i = j
    return (rank_sum - pos * (pos + 1) / 2) / (pos * neg)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default="artifacts/blind.jsonl")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    rows = [json.loads(l) for l in open(args.manifest)]
    y = [r["is_generalizer"] for r in rows]
    cert = [r["certificate_score"] for r in rows]
    vl = [r["val_loss"] for r in rows]
    pc = [r["param_count"] for r in rows]
    prev = sum(y) / len(y)
    rng = random.Random(args.seed)
    med = lambda v: sorted(v)[len(v) // 2]
    tau = CERTIFICATE["threshold_tau"]

    rows_out = []
    for name, pred, scores in [
        ("PIV certificate", [s >= tau for s in cert], cert),
        ("Always-positive", [True] * len(y), [1.0] * len(y)),
        ("Random (prevalence)", [rng.random() < prev for _ in y],
         [rng.random() for _ in y]),
        ("Val loss < median", [v < med(vl) for v in vl], [-v for v in vl]),
        ("Param count > median", [p > med(pc) for p in pc], pc),
    ]:
        m = metrics(pred, y)
        m["auroc"] = auroc(scores, y)
        rows_out.append((name, m))
        ci = m["ci_precision"]
        print(f"{name:24s} prec={m['precision']:.3f} "
              f"[{ci[0]:.3f},{ci[1]:.3f}] rec={m['recall']:.3f} "
              f"spec={m['specificity']:.3f} bal={m['balanced_acc']:.3f} "
              f"auroc={m['auroc']:.3f}  (tp,fp,fn,tn)={m['counts']}")

    os.makedirs("tables", exist_ok=True)
    with open("tables/blind_baselines.tex", "w") as f:
        f.write("% generated by scripts/blind_baselines.py\n")
        f.write("\\begin{tabular}{lccccc}\n\\toprule\n")
        f.write("Predictor & Prec. & Recall & Spec. & Bal.\\ Acc. & AUROC \\\\\n\\midrule\n")
        for name, m in rows_out:
            f.write(f"{name} & {m['precision']:.3f} & {m['recall']:.3f} & "
                    f"{m['specificity']:.3f} & {m['balanced_acc']:.3f} & "
                    f"{m['auroc']:.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote tables/blind_baselines.tex")

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        ths = sorted(set(cert)) + [max(cert) + 1]
        pts = []
        for th in ths:
            pred = [s >= th for s in cert]
            m = metrics(pred, y)
            pts.append((1 - m["specificity"], m["recall"]))
        pts.sort()
        os.makedirs("figures", exist_ok=True)
        fig, ax = plt.subplots(figsize=(4, 4))
        ax.plot([p[0] for p in pts], [p[1] for p in pts], "-o", ms=3)
        ax.plot([0, 1], [0, 1], "k--", lw=0.8)
        ax.set_xlabel("FPR"); ax.set_ylabel("TPR")
        ax.set_title(f"PIV certificate ROC (AUROC {auroc(cert, y):.3f})")
        fig.tight_layout(); fig.savefig("figures/roc_blind.pdf")
        print("wrote figures/roc_blind.pdf")
    except ImportError:
        print("matplotlib not installed; skipped figures/roc_blind.pdf")


if __name__ == "__main__":
    main()
